### ISSUE TITLE
Setup Errors

### ISSUE THREAD

**Issue by h4ck1th4rd** [makiisthenes/TiktokAutoUploader#1]
Hi, good work, I just get this below error:

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

**Comment by makiisthenes** [comment]
Yes, have you installed ImageMagick on your system,
 https://imagemagick.org/script/download.php

Then in site-packages, go to moviepy and edit config_defualts.py
![image](https://user-images.githubusercontent.com/52138450/111904491-27c92b00-8a3f-11eb-85ee-56bdcb4ac4c9.png)

**Comment by h4ck1th4rd** [comment]
Thank you, thats fixed the issue, Now its not posting. Its just upload, is there a way to make it post?

I am stuck here: https://gyazo.com/ba50ff4f4e1cd0d7d05a9edf9b6e02dc

**Comment by makiisthenes** [comment]
method uploadVideo(video_dir, videoText, startTime=0, endTime=0, private=True, test=True)

By defualt test=True meaning it will not upload and only stay preview for user to click upload.

Switching to test=False, it will upload.

**Comment by h4ck1th4rd** [comment]
I love active people like you who make a decent python codes.

**Comment by h4ck1th4rd** [comment]
My video is 0 to 8 length. but when I uploaded it only uploads 1 sec.

**Comment by makiisthenes** [comment]
Ok I'm looking at the method for cropping videos.

**Comment by makiisthenes** [comment]
I fixed this issue. Please only change parameters in Main().uploadVideo().

For example uploadVideo("myVideo", "Overlay Text", startTime=0, endTime=8, private=False, test=False):

**Comment by h4ck1th4rd** [comment]
Still not working. 1 sec video only.

**Comment by makiisthenes** [comment]
Is this not working on the new crop fix I posted, if not clone the latest repo again and try run it, I fixed and tested this issue?!?

**Comment by makiisthenes** [comment]
I just tested with fresh clone and it works perfectly. I don't know how I can help, I'm sorry.

**Comment by h4ck1th4rd** [comment]
Audio works, The video is not working.

**Comment by franzqat** [comment]
> 
> 
> Yes, have you installed ImageMagick on your system,
> https://imagemagick.org/script/download.php
> 
> Then in site-packages, go to moviepy and edit config_defualts.py
> ![image](https://user-images.githubusercontent.com/52138450/111904491-27c92b00-8a3f-11eb-85ee-56bdcb4ac4c9.png)
> 
> Change this auto to your path like shown in image above.
> Michael

I am still getting this problem. I tried to install both ImageMagick-7.1.0-0-Q16-HDRI-x64-dll.exe and ImageMagick-7.1.0-0-Q16-x64-dll.exe versions, tried to run with WLS and magick from there changing the settings accordingly but without success.

This is the error

> OSError: MoviePy Error: creation of None failed because of the following error:

> [WinError 2] Impossibile trovare il file specificato.

> .This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

**Comment by makiisthenes** [comment]
What is the path that you have specified?
