### ISSUE TITLE
TikTok Datacenter Allocation Error, Key Error 'project'

### ISSUE THREAD

**Issue by cjkehoe** [makiisthenes/TiktokAutoUploader#52]
Fails to login to upload video. 

Struggling to get past this error

(.venv) chriskehoe@Chriss-MacBook-Air TiktokAutoUploader % python cli.py upload --cookie SirPapiWysocki -v "test1.mp4" -t "My video title"
[{'domain': '.tiktok.com', 'expiry': 1723435627, 'httpOnly': True, 'name': 'sessionid', 'path': '/', 'sameSite': 'Lax', 'secure': True, 'value': '5c6e703788f1332160bd11b6f06b1be4'}]
Traceback (most recent call last):
  File "/Users/chriskehoe/Projects/TiktokAutoUploader/cli.py", line 68, in <module>
    tiktok.upload_video(session_id, args.video,  args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel, args.proxy)
  File "/Users/chriskehoe/Projects/TiktokAutoUploader/tiktok_uploader/tiktok.py", line 91, in upload_video
    project_id = r.json()["project"]["project_id"]
KeyError: 'project'

I think it's an error with the session id? But I am not sure. Logging into tiktok manually and comparing my session id compared to the session id stored locally it is different. However manually modifying the local session id seems to corrupt the file. Not sure what I am doing wrong.

**Comment by makiisthenes** [comment]
Please note you have just exposed your session id, which is linked to your tiktok account, please remove session id from the error log. I will aid in your problem in a whie.

**Comment by Festouille** [comment]
Got the same problem ! Now i'm logged in but can't upload videos, by youtube directly, or by giving a path, 
![a](https://github.com/makiisthenes/TiktokAutoUploader/assets/115322112/02effbe2-7b4e-4978-a378-d19461feecc2)

![image](https://github.com/makiisthenes/TiktokAutoUploader/assets/115322112/8af68f3b-eac6-4304-bd1c-fe051cdaa9da)

![image](https://github.com/makiisthenes/TiktokAutoUploader/assets/115322112/29a9b4c8-6820-45ef-9118-e5084349c849)

Thank you.

**Comment by makiisthenes** [comment]
Have you cloned the latest commit?

**Comment by Festouille** [comment]
yes i did

**Comment by Festouille** [comment]
![a](https://github.com/makiisthenes/TiktokAutoUploader/assets/115322112/36946900-eed6-4695-8390-d429585d6f49)

**Comment by makiisthenes** [comment]
Latest merge has solved the cli issue.

**Comment by makiisthenes** [comment]
Please print out r.json() at the error line as I am not able to replicate this error

**Comment by Festouille** [comment]
`PS C:\Users\akram\TiktokAutoUploader> python cli.py upload -u festouille -v "pre-processed.mp4" -t "Ben"
User successfully logged in.
Uploading video...
{'log_pb': {'impr_id': '20240214163037DD0B3EFA9BC0847778FA'}, 'status_code': 8, 'status_msg': 'Login expired'}
Traceback (most recent call last):
  File "C:\Users\akram\TiktokAutoUploader\cli.py", line 82, in <module>
    tiktok.upload_video(session_id, args.video,  args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel, args.proxy)
  File "C:\Users\akram\TiktokAutoUploader\tiktok_uploader\tiktok.py", line 91, in upload_video
    project_id = r.json()["project"]["project_id"]
                 ~~~~~~~~^^^^^^^^^^^
KeyError: 'project'`

**Comment by Festouille** [comment]
![image](https://github.com/makiisthenes/TiktokAutoUploader/assets/115322112/5ff48cec-68ff-4921-aaf6-23920fc678e2)

I don't know if u seen my screenshot because on my point of view I don't see it.

**Comment by cooldude3828** [comment]
same here:

User successfully logged in.
Uploading video...
Traceback (most recent call last):
  File "C:\Users\messi\Documents\TiktokAutoUploader\cli.py", line 82, in <module>  
    tiktok.upload_video(session_id, args.video,  args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel, args.proxy)
  File "C:\Users\messi\Documents\TiktokAutoUploader\tiktok_uploader\tiktok.py", line 90, in upload_video
    project_id = r.json()["project"]["project_id"]
                 ~~~~~~~~^^^^^^^^^^^
KeyError: 'project'

**Comment by cooldude3828** [comment]
seems to be grabbing a different sessionid...

**Comment by hypefi** [comment]
same here, login expired 

User successfully logged in.
Uploading video...
{'log_pb': {'impr_id': '202402151036402E6976406F6B7C0FCB68'}, 'status_code': 8, 'status_msg': 'Login expired'}
Traceback (most recent call last):
  File "/Users/mac/WORK/CODE/MISC/tiktok_upload_cli/TiktokAutoUploader/cli.py", line 82, in <module>
    tiktok.upload_video(session_id, args.video,  args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel, args.proxy)
  File "/Users/mac/WORK/CODE/MISC/tiktok_upload_cli/TiktokAutoUploader/tiktok_uploader/tiktok.py", line 91, in upload_video
    project_id = r.json()["project"]["project_id"]
                 ~~~~~~~~^^^^^^^^^^^

**Comment by hypefi** [comment]
ok got it, for me I needed to change the tt-target-idc to useast1a instead of useast2a in the line : session.cookies.set("tt-target-idc", "useast1a", domain=".tiktok.com")
check your cookies in your session in developer tools, but the code needs to be updated to take into account the tt-target-idc

**Comment by makiisthenes** [comment]
This bug is location dependant and this type of fix will not aid everyone.

**Comment by makiisthenes** [comment]
> ok got it, for me I needed to change the tt-target-idc to useast1a instead of useast2a in the line : session.cookies.set("tt-target-idc", "useast1a", domain=".tiktok.com") check your cookies in your session in developer tools, but the code needs to be updated to take into account the tt-target-idc

Thank you for this, I have now updated the code to handle the dynamic datacenter locations, please pull latest commit.

**Comment by Festouille** [comment]
![image](https://github.com/makiisthenes/TiktokAutoUploader/assets/115322112/045c41b4-acc2-487c-ab96-88e53e7b37da)


Worked using Python 3.10 !

**Comment by HoTruong** [comment]
> ![image](https://private-user-images.githubusercontent.com/115322112/305185350-045c41b4-acc2-487c-ab96-88e53e7b37da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODk5MTYsIm5iZiI6MTcwODA4OTYxNiwicGF0aCI6Ii8xMTUzMjIxMTIvMzA1MTg1MzUwLTA0NWM0MWI0LWFjYzItNDg3Yy1hYjk2LTg4ZTUzZTdiMzdkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxMzIwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjExZThhZGQ2ODI5N2RkODAwMzVkMTNmYWE4MzU4Mjc3NGJmZjBiMzA3MDA0YjQ1ZDE0ZTIwYmY3MGE2ZDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TOzywOjRNrESBZv-8VB8EVncHn6N2MvAYN3rAfM0-6Q)
> 
> Worked using Python 3.10 !

I using python 3.10.10 with latest source commit. But getting the following error. Does anyone know how to fix it?
![image](https://github.com/makiisthenes/TiktokAutoUploader/assets/31133376/5e2c11ec-b472-40d7-b51f-4a628c2d634b)

**Comment by johnathanchiu** [comment]
I believe this issue still exists. I just cloned the repo and tried it. Still doesn't work.

**Comment by bigdog765** [comment]
Just started getting this error after using it continuously for a while, it started on July 13th
